[project]
name = "decn-ticketing"
description = "Decentralized ticketing system"
authors = []
telemetry = false

[contracts.ticketing]
path = "contracts/ticketing.clar"

[[accounts]]
name = "deployer"
balance = 100000000000  # 1000 STX

[[accounts]]
name = "wallet_1"
balance = 100000000000  # 1000 STX

[[accounts]]
name = "wallet_2"
balance = 50000000000   # 500 STX